### [순환신경망 RNN] <hr> 

In [1]:
import torch
import torch.nn as nn

c:\ProgramData\anaconda3\envs\Torch_NLP38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\ProgramData\anaconda3\envs\Torch_NLP38\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\ProgramData\anaconda3\envs\Torch_NLP38\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
HIDDEN_SIZE = 1
NUM_LAYERS = 1
SEQ_LENGTH = 3
BATCH_SIZE = 1

# 데이터 및 초기 hidden state
input = torch.randn(1, 3, 10)  # 입력데이터(배치크기, 시퀀스길이, 피처길이)

# 첫번째 hidden state 초기값
h0 = torch.randn(NUM_LAYERS, BATCH_SIZE, HIDDEN_SIZE)  # 히든 초기값(양방향*층수, 배치크기, 히든개수)

# RNN 인스턴스 생성
rnn = nn.RNN(10, HIDDEN_SIZE, NUM_LAYERS, batch_first = True)

# RNN 출력
output, hn = rnn(input, h0)

In [3]:
print(f'RNN 출력 - input\n-SHAPE ; {input.shape}  DIM : {input.ndim}D')
print(output)

RNN 출력 - input
-SHAPE ; torch.Size([1, 3, 10])  DIM : 3D
tensor([[[-0.8937],
         [ 1.0000],
         [ 0.9706]]], grad_fn=<TransposeBackward1>)


In [4]:
print(f'RNN 출력 - output\n- SHAPE ; {output.shape}  DIM : {output.ndim}D')

RNN 출력 - output
- SHAPE ; torch.Size([1, 3, 1])  DIM : 3D


In [5]:
print(f'RNN 출력 - hidden state\n- SHAPE : {hn.shape}  DIM : {hn.ndim}D')

RNN 출력 - hidden state
- SHAPE : torch.Size([1, 1, 1])  DIM : 3D


In [6]:
print('[RNN parameters]')
for name, param in rnn.named_parameters():
    print(f'---------[{name}] \n{param}]') 
# 같은 층에 있는 HS끼리 상호작용해서 절편 계산 ex) HIDDEN_SIZE = 3 : bias 수 = 9

[RNN parameters]
---------[weight_ih_l0] 
Parameter containing:
tensor([[-0.2801,  0.5060,  0.3781,  0.8186, -0.0749,  0.7480, -0.8409,  0.9773,
          0.9864, -0.7522]], requires_grad=True)]
---------[weight_hh_l0] 
Parameter containing:
tensor([[-0.3206]], requires_grad=True)]
---------[bias_ih_l0] 
Parameter containing:
tensor([0.0843], requires_grad=True)]
---------[bias_hh_l0] 
Parameter containing:
tensor([0.4089], requires_grad=True)]


In [7]:
# rnn 모델의 속성 출력
print(f'[all_weights] : {len(rnn.all_weights)}')
print(rnn.all_weights)

[all_weights] : 1
[[Parameter containing:
tensor([[-0.2801,  0.5060,  0.3781,  0.8186, -0.0749,  0.7480, -0.8409,  0.9773,
          0.9864, -0.7522]], requires_grad=True), Parameter containing:
tensor([[-0.3206]], requires_grad=True), Parameter containing:
tensor([0.0843], requires_grad=True), Parameter containing:
tensor([0.4089], requires_grad=True)]]


In [14]:
# 설계 : 다층 RNN, 층 2개

# 입력 초기 텐서 2개
input = torch.randn(1, 4, 10)  # (배치크기, 시퀀스(문장의 단어 수), 피처수(단어 표현 벡터 길이))
h0 = torch.randn(1, 1, 5)      # (양방향*층수, 배치크기, 은닉상태 사이즈) => 은닉상태 초기화
    
# RNN 인스턴스
rnn = nn.RNN(10, 5, 1, batch_first = True)

# 출력 텐서 2개
output, hn = rnn(input, h0)

In [9]:
from torchinfo import summary
summary(rnn)

Layer (type:depth-idx)                   Param #
RNN                                      85
Total params: 85
Trainable params: 85
Non-trainable params: 0

In [10]:
# RNN 모델의 속성 출력
print(f'[all_weight] - {len(rnn.all_weights)}개')
print(rnn.all_weights) 

[all_weight] - 1개
[[Parameter containing:
tensor([[ 0.1958,  0.0342,  0.1034,  0.2363,  0.0756, -0.0588, -0.3562,  0.1562,
         -0.2359,  0.2448],
        [-0.1322,  0.1767, -0.1304,  0.3581,  0.0546,  0.2111, -0.2511,  0.3301,
         -0.3411, -0.1392],
        [ 0.2734,  0.0196, -0.0172, -0.3432, -0.4229, -0.1259,  0.3792,  0.2397,
         -0.3848, -0.3218],
        [-0.0103,  0.3612,  0.2424, -0.1678,  0.3566, -0.3632, -0.0066,  0.3210,
         -0.3941,  0.2751],
        [ 0.1973,  0.0683,  0.4365, -0.1351, -0.3765, -0.0821,  0.1483, -0.1286,
          0.3877, -0.3159]], requires_grad=True), Parameter containing:
tensor([[-0.1741,  0.0997, -0.1331,  0.2875, -0.4213],
        [ 0.2911,  0.3310, -0.1712,  0.4128, -0.3041],
        [-0.1420,  0.4036, -0.3939,  0.2749,  0.3197],
        [-0.1662, -0.1371, -0.2393, -0.2761, -0.3180],
        [ 0.0038,  0.1257, -0.0192,  0.3208,  0.0854]], requires_grad=True), Parameter containing:
tensor([-0.4394,  0.2575, -0.1999,  0.1439, -0.328

In [11]:
# RNN 출력 텐서 output
output.shape, output.ndim, output

(torch.Size([1, 4, 5]),
 3,
 tensor([[[-0.6005, -0.0812, -0.3265, -0.8692, -0.3442],
          [-0.0205,  0.4382, -0.9329,  0.6194, -0.9430],
          [ 0.4551,  0.7747, -0.7934,  0.1805, -0.7322],
          [ 0.0805,  0.7653, -0.9527, -0.3127, -0.6572]]],
        grad_fn=<TransposeBackward1>))