### [순환신경망 RNN] <hr> 

In [15]:
import torch
import torch.nn as nn

In [17]:
# 설계 : 다층 RNN, 층 2개

# 입력 초기 텐서 2개
input = torch.randn(1, 4, 10)  # (배치크기, 시퀀스(문장의 단어 수), 피처수(단어 표현 벡터 길이))
h0 = torch.randn(1, 1, 5)      # (양방향*층수, 배치크기, 은닉상태 사이즈) => 은닉상태 초기화
    
# RNN 인스턴스
rnn = nn.RNN(10, 5, 1, batch_first = True)

# 출력 텐서 2개
output, hn = rnn(input, h0)

In [18]:
from torchinfo import summary
summary(rnn)

Layer (type:depth-idx)                   Param #
RNN                                      85
Total params: 85
Trainable params: 85
Non-trainable params: 0

In [19]:
# RNN 모델의 속성 출력
print(f'[all_weight] - {len(rnn.all_weights)}개')
print(rnn.all_weights) 

[all_weight] - 1개
[[Parameter containing:
tensor([[-0.3224, -0.1418,  0.4052, -0.0110,  0.1479, -0.1539,  0.2513,  0.1205,
          0.3636,  0.1735],
        [ 0.1575,  0.2538, -0.3683, -0.4131,  0.0695, -0.0039, -0.3979, -0.0614,
          0.2701,  0.0350],
        [ 0.3616, -0.3521,  0.4222, -0.0956,  0.1027, -0.0795, -0.4467,  0.3857,
          0.3413,  0.1578],
        [ 0.0701, -0.0291,  0.1326,  0.0858, -0.3691, -0.4195,  0.1649,  0.3218,
          0.3619, -0.1413],
        [ 0.1680, -0.1357, -0.1454, -0.3771, -0.2462,  0.3328,  0.3596,  0.2027,
          0.0826, -0.3496]], requires_grad=True), Parameter containing:
tensor([[ 0.3279,  0.1217, -0.4381, -0.3658,  0.0881],
        [ 0.1091, -0.0135, -0.1729,  0.3816,  0.2752],
        [ 0.0796,  0.3542, -0.1177,  0.4434,  0.0814],
        [ 0.3516, -0.0199, -0.3874,  0.4148,  0.3545],
        [ 0.2178,  0.0629,  0.3802,  0.0032, -0.2650]], requires_grad=True), Parameter containing:
tensor([ 0.1675,  0.4403, -0.1317, -0.1478,  0.235

In [20]:
# RNN 출력 텐서 output
output.shape, output.ndim, output

(torch.Size([5, 4, 5]),
 3,
 tensor([[[ 5.6085e-01,  9.4945e-01, -9.3677e-01,  3.8588e-01, -9.4698e-01],
          [ 4.0996e-01, -4.1684e-01, -9.4800e-01, -4.0726e-01,  4.7474e-01],
          [ 3.2873e-01,  8.8313e-01,  8.2205e-01, -6.2061e-02, -9.5551e-01],
          [-7.0305e-04,  8.8722e-03,  7.7351e-01,  1.2388e-01, -4.6737e-01]],
 
         [[ 8.7874e-01,  9.5629e-01,  9.9482e-01,  9.2626e-01, -4.6630e-01],
          [ 7.8179e-01,  9.2788e-01, -7.8786e-01, -3.1325e-01, -9.0800e-01],
          [ 3.1930e-01, -5.2312e-01, -9.9555e-01, -4.1501e-01,  9.8211e-01],
          [ 8.7049e-01, -3.6190e-01, -7.5540e-01,  5.7641e-01, -3.5746e-01]],
 
         [[-4.7080e-01,  8.0589e-01,  5.4769e-01,  1.0031e-01,  8.5102e-01],
          [-6.5642e-01,  9.1403e-01, -3.5373e-01, -8.8430e-01,  5.6918e-01],
          [ 6.7310e-01,  3.5495e-01, -7.8594e-01,  9.3930e-01, -2.4043e-01],
          [ 9.4396e-01,  9.1079e-01,  8.9717e-01, -3.2196e-02,  5.3892e-02]],
 
         [[-4.9944e-01,  9.3127e-01,  2